# -*- coding: utf-8 -*-
"""GPA To Marks

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xhrXW60Tu5UJF5rbzOC9LYS2Td-S_NZA
"""

GPA_to_pointer ={ 'A+' :4.0, 'A' :4.0, 'A-' :3.67, 'B+':3.33, 'B' :3.0, 'B-' :2.67,
                 'C+' :2.33, 'C' :2.0, 'C-' :1.67, 'D+' :1.33, 'D' :1.0, 'F' :0.0}
num_courses = 0
total_points = 0
GPA = input()

if GPA not in GPA_to_pointer: # unrecognized grade entered 
    print("Unknown GPA {0} being ignored".format(GPA))
else:
    num_courses += 1
    total_points += GPA_to_pointer[GPA]
if num_courses > 0: # avoid division by zero
    print( 'Your GPA is {0:.3}' .format(total_points / num_courses))